import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/modules/Home.module.css'
import * as React from 'react'

const Home: NextPage = () => {
  return (
  <div>
    <div className={styles.container}>
      <Head>
        <title>Tortuga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>

    <div className={styles.container}>

    </div>
  </div>
  )
}

export default Home
